def raise_exception():
    x = "hello"
    y = 42

    result = x + y
    